[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
umich_predictions = "eioYwjxzGasyXTBJQ6aRJFFczARqj6yXPxMvFr56swK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
